---

- name: Install ethtool
  become: yes
  package:
    name: ethtool
    state: present

- name: Create if-post-up directory
  become: yes
  file:
    state: directory
    path: /etc/network/if-post-up.d
    owner: root
    group: root
    mode: 0755

- name: Create if-post-up script
  become: yes
  template:
    src: tcp_offload.sh.j2
    dest: /etc/network/if-post-up.d/tcp_offload.sh
    owner: root
    group: root
    mode: 0755
  notify:
    - restart network
