---

- name: Prepare
  hosts: all
  gather_facts: no

  tasks:
  - name: Update package cache
    package: update_cache=yes
    changed_when: false
    register: task_result
    until: task_result is success
    retries: 10
    delay: 2
