---

default_fs_type: xfs

dev_mapping:
    # /dev/sda:
    # mount_path: /
    # fs_type: ext4

    - dev_name: /dev/sdb
      fs_type: lvm

    - dev_name: /dev/sdc
      fs_type: lvm

    - dev_name: /dev/sdd
      mount_path: /opt

    - dev_name: /dev/sde
      mount_path: /tmp

    # - dev_name: /dev/sdf
    #   mount_path: 
    #   fs_type: xfs

    - dev_name: /dev/sdg
      mount_path: /data/01
      mnt_opts: 'defaults,noatime,nofail'

    - dev_name: /dev/sdh
      mount_path: /data/02
      mnt_opts: 'defaults,noatime,nofail'

    - dev_name: /dev/sdi
      mount_path: /data/03
      mnt_opts: 'defaults,noatime,nofail'

    - dev_name: /dev/sdj
      mount_path: /data/04
      mnt_opts: 'defaults,noatime,nofail'

    - dev_name: /dev/sdk
      mount_path: /data/05
      mnt_opts: 'defaults,noatime,nofail'

    - dev_name: /dev/sdl
      mount_path: /data/06
      mnt_opts: 'defaults,noatime,nofail'

    - dev_name: /dev/sdm
      mount_path: /data/07
      mnt_opts: 'defaults,noatime,nofail'

    - dev_name: /dev/sdn
      mount_path: /data/08
      mnt_opts: 'defaults,noatime,nofail'

    - dev_name: /dev/sdo
      mount_path: /data/09
      mnt_opts: 'defaults,noatime,nofail'

    - dev_name: /dev/sdp
      mount_path: /data/10
      mnt_opts: 'defaults,noatime,nofail'

    - dev_name: /dev/sdq
      mount_path: /data/11
      mnt_opts: 'defaults,noatime,nofail'

    - dev_name: /dev/sdr
      mount_path: /data/12
      mnt_opts: 'defaults,noatime,nofail'

    - dev_name: /dev/sds
      mount_path: /data/13
      mnt_opts: 'defaults,noatime,nofail'

    - dev_name: /dev/sdt
      mount_path: /data/14
      mnt_opts: 'defaults,noatime,nofail'

    - dev_name: /dev/sdu
      mount_path: /data/15
      mnt_opts: 'defaults,noatime,nofail'

    - dev_name: /dev/sdv
      mount_path: /data/16
      mnt_opts: 'defaults,noatime,nofail'

    - dev_name: /dev/sdw
      mount_path: /data/17
      mnt_opts: 'defaults,noatime,nofail'

    - dev_name: /dev/sdx
      mount_path: /data/18
      mnt_opts: 'defaults,noatime,nofail'

    - dev_name: /dev/sdy
      mount_path: /data/19
      mnt_opts: 'defaults,noatime,nofail'

    - dev_name: /dev/sdz
      mount_path: /data/20
      mnt_opts: 'defaults,noatime,nofail'

volume_groups:
  - name: vg.data
    pvs: /dev/sdb,/dev/sdc

logical_volumes:
  - name: lv.home.user1
    vg: vg.data
    size: 500M
    mount_path: /home/user1

  - name: lv.home.user2
    vg: vg.data
    size: 400M
    mount_path: /home/user2
