---

- name: Init infra
  hosts: localhost
  connection: local
  gather_facts: no

  roles:
  - role: cloud-infra
    vars:
      state: present
      template_inventory: 'molecule_gce_instances.gcp.yml.j2'
      template_tfvars: 'molecule_tfvars.json.j2'
      terraform_project_repo: 'https://github.com/klusters/terraform-tools-gce-molecule'
