---
- name: Create
  hosts: localhost
  connection: local
  gather_facts: no

  vars:
    terraform_dir: "{{ playbook_dir }}/../terraform"

  pre_tasks:
  - name: Generate GCP dynamic inventory file
    template:
      src: gce_instances.gcp.yml.j2
      dest: gce_instances.gcp.yml
      mode: 0644

  - name: Get Terraform scripts
    git:
      repo: 'https://github.com/klusters/terraform-tools-gce-molecule'
      dest: '{{ terraform_dir }}'
      version: main

  tasks:
  - name: Generate Terraform vars
    copy:
      dest: '{{ terraform_dir }}/terraform.tfvars.json'
      content: "{{ molecule_yml.platforms[0] }}"
      mode: '0644'

  - name: Terraform apply
    terraform:
      binary_path: "{{ lookup('env','TERRAFORM_CLI_PATH') + '/terraform-bin' |default(omit) }}"
      force_init: yes
      project_path: '{{ terraform_dir }}'
      workspace: "{{ lookup('env','MOLECULE_DISTRO') + '-' + lookup('env','GITHUB_RUN_NUMBER') |default('default') }}"
      state: present
