---

- name: Init infra
  hosts: localhost
  connection: local
  gather_facts: no

  roles:
  - role: cloud-infra
    vars:
      state: present
      instances: '{{ molecule_yml.platforms }}'
      template_inventory: 'molecule_gce_instances.gcp.yml.j2'