---

- name: Destroy infra
  hosts: localhost
  connection: local
  gather_facts: no

  roles:
  - role: cloud-infra
    vars:
      state: absent
      terraform_project_repo: 'https://github.com/klusters/terraform-tools-gce-molecule'
