---


- name: Install rng-tools
  package:
    name: rng-tools
    state: present

- name: Configure rngd to use random number source device
  template:
    src: rngd.sysconfig.j2
    dest: /etc/sysconfig/rngd
    owner: root
    group: root
    mode: 0644
  notify:
    - restart rngd

- name: Configure rngd to use random number source device
  template:
    src: rngd.service.j2
    dest: /etc/systemd/system/rngd.service
    owner: root
    group: root
    mode: 0644
  notify:
    - daemon reload

- name: Ensure that the rngd service is enabled and started at boot time
  service:
    name: rngd
    enabled: yes
    state: started
