---

- name: Install rng-tools
  become: yes
  ansible.builtin.package:
    name: rng-tools
    state: present

- name: Configure rngd to use random number source device
  become: yes
  ansible.builtin.template:
    src: rngd.service.j2
    dest: /etc/systemd/system/rngd.service
    owner: root
    group: root
    mode: 0644
  notify:
    - restart rngd
