---

- name: Converge
  hosts: all

  roles:
  - role: klusters.system.filesystems
    vars:
      default_fs_type: xfs
      logical_volumes: [] # no /dev/mapper in container, cannot test lv creation
      volume_groups:
        - name: vg.data
          pvs: /dev/loop0,/dev/loop1

      dev_mapping:
      - dev_name: /dev/loop0
        fs_type: lvm

      - dev_name: /dev/loop1
        fs_type: lvm

      - dev_name: /dev/loop2
        mount_path: /var/log

      - dev_name: /dev/loop3
        mount_path: /tmp

      - dev_name: /dev/loop4
        mount_path: /data/01
        mnt_opts: 'defaults,noatime,nofail'

...