---
- name: Converge
  hosts: "{{ lookup('env','MOLECULE_SCENARIO_NAME') }}-{{ lookup('env','MOLECULE_DISTRO') }}-001"
  pre_tasks:
    - debug:
        msg: "{{ ansible_devices.keys() }}"
  roles:
    - role: klusters.system.filesystems
  post_tasks:
    - name: gather
      setup:
    - debug:
        msg: "{{ ansible_mounts }}"
