---
- name: Create
  hosts: localhost
  connection: local
  gather_facts: false
  become: yes
  vars:
    terraform_dir: '{{ playbook_dir }}/terraform'

  pre_tasks:
  - name: Get Terraform scripts
    git:
      repo: 'https://github.com/klusters/terraform-tools-gce-molecule'
      dest: '{{ terraform_dir }}'
      version: master

  tasks:
  - name: Generate Terraform vars
    copy:
      dest: '{{ terraform_dir }}/terraform.tfvars.json'
      content: "{{ molecule_yml.platforms[0] }}"
      mode: '644'

  - name: Terraform apply
    terraform:
      binary_path: "{{ lookup('env','TERRAFORM_CLI_PATH') + '/terraform-bin' |default(omit) }}"
      force_init: yes
      project_path: '{{ terraform_dir }}'
      state: present
    environment:
      GOOGLE_CREDENTIALS: "{{ lookup('env','GOOGLE_APPLICATION_CREDENTIALS')}}"
