---
- name: Create
  hosts: localhost
  connection: local
  gather_facts: false

  vars:
    terraform_dir: 'ansible_collections/klusters/system/terraform'

  pre_tasks:
  - name: Get Terraform scripts
    git:
      repo: 'https://github.com/klusters/terraform-tools-gce-molecule'
      dest: '{{ terraform_dir }}'
      version: master

  tasks:
  - name: Generate Terraform vars
    copy:
      dest: '{{ terraform_dir }}/terraform.tfvars.json'
      content: "{{ molecule_yml.platforms[0] }}"
      mode: '644'

  - name: Terraform apply
    terraform:
      binary_path: "{{ lookup('env','TERRAFORM_PATH')|default(omit) }}"
      project_path: '{{ terraform_dir }}'
      force_init: yes
      state: present
