---
- name: Create
  hosts: localhost
  connection: local
  gather_facts: false
  become: yes
  vars:
    terraform_dir: "{{ playbook_dir }}/terraform/{{ lookup('env','MOLECULE_SCENARIO_NAME') + '-' + lookup('env','MOLECULE_DISTRO') |default('default') }}"

  pre_tasks:
  - name: Get Terraform scripts
    git:
      repo: 'https://github.com/klusters/terraform-tools-gce-molecule'
      dest: '{{ terraform_dir }}'
      version: master

  tasks:
  - name: Generate Terraform vars
    copy:
      dest: '{{ terraform_dir }}/terraform.tfvars.json'
      content: "{{ molecule_yml.platforms[0] }}"
      mode: '644'

  - name: Terraform apply
    terraform:
      binary_path: "{{ lookup('env','TERRAFORM_CLI_PATH') + '/terraform-bin' |default(omit) }}"
      force_init: yes
      project_path: '{{ terraform_dir }}'
      workspace: "{{ lookup('env','MOLECULE_SCENARIO_NAME') + '-' + lookup('env','MOLECULE_DISTRO') |default('default') }}"
      state: present
    environment:
      TF_VAR_project_id: "{{ lookup('env','TF_VAR_project_id') }}"
      GOOGLE_CREDENTIALS: "{{ lookup('env','GOOGLE_APPLICATION_CREDENTIALS') }}"
      TF_VAR_ssh_key_name: "{{ lookup('env','MOLECULE_SCENARIO_NAME') + '-' + lookup('env','MOLECULE_DISTRO') + '-001' | default(omit) }}"
      TF_VAR_ssh_key_path: "{{ lookup('env','GITHUB_WORKSPACE') | default(omit) }}"