---
- name: Destroy
  hosts: localhost
  connection: local
  gather_facts: false
  vars:
    terraform_dir: '{{ playbook_dir }}/terraform'
  tasks:
  - name: Terraform destroy
    terraform:
      binary_path: "{{ lookup('env','TERRAFORM_CLI_PATH') + '/terraform-bin' |default(omit) }}"
      project_path: '{{ terraform_dir }}'
      state: absent
