---
- name: Destroy
  hosts: localhost
  connection: local
  gather_facts: false
  vars:
    terraform_dir: '{{ playbook_dir }}/terraform_destroy'
  pre_tasks:
  - name: Get Terraform scripts
    git:
      repo: 'https://github.com/klusters/terraform-tools-gce-molecule'
      dest: '{{ terraform_dir }}'
      version: master

  tasks:
  - name: Terraform destroy
    terraform:
      binary_path: "{{ lookup('env','TERRAFORM_CLI_PATH') + '/terraform-bin' |default(omit) }}"
      project_path: '{{ terraform_dir }}'
      force_init: yes
      workspace: "{{ lookup('env','MOLECULE_DISTRO') |default('default') }}"
      state: absent
    environment:
      TF_VAR_project_id: "{{ lookup('env','TF_VAR_project_id') }}"
      GOOGLE_CREDENTIALS: "{{ lookup('env','GOOGLE_APPLICATION_CREDENTIALS') }}"
