---
- name: Destroy
  hosts: localhost
  connection: local
  gather_facts: false
  vars:
    terraform_dir: "{{ playbook_dir }}/terraform_destroy/{{ lookup('env','MOLECULE_SCENARIO_NAME') +
    '-' + lookup('env','MOLECULE_DISTRO') |default('default') }}"

  pre_tasks:
  - name: Get Terraform scripts
    git:
      repo: 'https://github.com/klusters/terraform-tools-gce-molecule'
      dest: '{{ terraform_dir }}'
      version: master

  tasks:
  - name: Terraform destroy
    terraform:
      binary_path: "{{ lookup('env','TERRAFORM_CLI_PATH') + '/terraform-bin' |default(omit) }}"
      project_path: '{{ terraform_dir }}'
      workspace: "{{ lookup('env','MOLECULE_SCENARIO_NAME') + '-' + lookup('env','MOLECULE_DISTRO') |default('default') }}"
      force_init: yes
      state: absent
    environment:
      TF_VAR_project_id: "{{ lookup('env','TF_VAR_project_id') }}"
      GOOGLE_CREDENTIALS: "{{ lookup('env','GOOGLE_APPLICATION_CREDENTIALS') }}"
      TF_VAR_ssh_key_name: "{{ lookup('env','MOLECULE_SCENARIO_NAME') + '-' + lookup('env','MOLECULE_DISTRO') + '-001' | default(omit) }}"
      TF_VAR_ssh_key_path: "{{ lookup('env','HOME') }}/.ssh"
