plugin: gcp_compute
projects:
  - feisty-catcher-261412
filters: []
auth_kind: serviceaccount
scopes:
 - 'https://www.googleapis.com/auth/cloud-platform'
 - 'https://www.googleapis.com/auth/compute.readonly'
hostnames:
  - name
compose:
  ansible_host: networkInterfaces[0].accessConfigs[0].natIP