---

dependency:
  name: galaxy

driver:
  name: delegated

lint: |
  yamllint .
  ansible-lint

platforms:
- name: instance-offloading-001
  instance_name: instance-offloading
  region: europe-west1
  zone: europe-west1-c
  network: default
  subnetwork: default
  machine_type: f1-micro
  image: centos-7
  additional_disks:
  - auto_delete: yes
    boot: no
    disk_size_gb: 1
    disk_type: pd-standard

  - auto_delete: yes
    boot: no
    disk_size_gb: 1
    disk_type: pd-standard

  - auto_delete: yes
    boot: no
    disk_size_gb: 1
    disk_type: pd-standard

  - auto_delete: yes
    boot: no
    disk_size_gb: 1
    disk_type: pd-standard

  - auto_delete: yes
    boot: no
    disk_size_gb: 1
    disk_type: pd-standard

  - auto_delete: yes
    boot: no
    disk_size_gb: 1
    disk_type: pd-standard

  - auto_delete: yes
    boot: no
    disk_size_gb: 1
    disk_type: pd-standard

  - auto_delete: yes
    boot: no
    disk_size_gb: 1
    disk_type: pd-standard

  - auto_delete: yes
    boot: no
    disk_size_gb: 1
    disk_type: pd-standard

  - auto_delete: yes
    boot: no
    disk_size_gb: 1
    disk_type: pd-standard

  - auto_delete: yes
    boot: no
    disk_size_gb: 1
    disk_type: pd-standard

  - auto_delete: yes
    boot: no
    disk_size_gb: 1
    disk_type: pd-standard

provisioner:
  name: ansible
  playbooks:
    converge: ${MOLECULE_PLAYBOOK:-converge.yml}
  connection_options:
    ansible_ssh_user: "github-ci"
    ansible_ssh_private_key_file: "/github/workspace/terraform/eg-test-molecule.pem"
  ansible_args:
    - --inventory=./gce_instances.gcp.yml

scenario:
  name: filesystems
  test_sequence:
    - lint
    # - destroy
    - dependency
    - syntax
    - create
    - prepare
    - converge
    - idempotence
    - verify
    - destroy
