---

dependency:
  name: galaxy

driver:
  name: delegated

lint: |
  yamllint .
  ansible-lint

platforms:
- name: ${MOLECULE_SCENARIO_NAME}-${MOLECULE_DISTRO}-001
  instance_name: ${MOLECULE_SCENARIO_NAME}-${MOLECULE_DISTRO}
  region: europe-west1
  network: default
  subnetwork: default
  machine_type: f1-micro
  image: ${MOLECULE_DISTRO}
  image_project: ${MOLECULE_DISTRO_PROJECT}
  additional_disks:
  - auto_delete: yes
    boot: no
    disk_size_gb: 1
    disk_type: pd-standard

  - auto_delete: yes
    boot: no
    disk_size_gb: 1
    disk_type: pd-standard

  - auto_delete: yes
    boot: no
    disk_size_gb: 1
    disk_type: pd-standard

  - auto_delete: yes
    boot: no
    disk_size_gb: 1
    disk_type: pd-standard

  - auto_delete: yes
    boot: no
    disk_size_gb: 1
    disk_type: pd-standard

  - auto_delete: yes
    boot: no
    disk_size_gb: 1
    disk_type: pd-standard

  - auto_delete: yes
    boot: no
    disk_size_gb: 1
    disk_type: pd-standard

  - auto_delete: yes
    boot: no
    disk_size_gb: 1
    disk_type: pd-standard

  - auto_delete: yes
    boot: no
    disk_size_gb: 1
    disk_type: pd-standard

  - auto_delete: yes
    boot: no
    disk_size_gb: 1
    disk_type: pd-standard

  - auto_delete: yes
    boot: no
    disk_size_gb: 1
    disk_type: pd-standard

  - auto_delete: yes
    boot: no
    disk_size_gb: 1
    disk_type: pd-standard

provisioner:
  name: ansible
  playbooks:
    converge: ${MOLECULE_PLAYBOOK:-converge.yml}
  connection_options:
    ansible_ssh_user: "github-ci"
    ansible_ssh_private_key_file: "/opt/hostedtoolcache/github-ci-${MOLECULE_SCENARIO_NAME}-${MOLECULE_DISTRO}-001.pem"
    ansible_ssh_common_args: -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null
  ansible_args:
    - --inventory=./gce_instances.gcp.yml

scenario:
  name: filesystems
  test_sequence:
    - lint
    # - destroy
    - dependency
    - syntax
    - create
    - prepare
    - converge
    - idempotence
    - verify
    - destroy
