---

- name: Prepare
  hosts: "{{ lookup('env','MOLECULE_SCENARIO_NAME') }}-{{ lookup('env','MOLECULE_DISTRO') }}-001"
  gather_facts: no
  pre_tasks:

  - name: Install gce dependency on controlling host (virtualenv)
    pip:
      name:
      - google-auth
      - jmespath
    delegate_to: 127.0.0.1

  - name: Fix ssh key permissions
    file:
      path: "/opt/hostedtoolcache/ssh/{{ lookup('env','TF_VAR_ssh_key_name') }}.pem"
      mode: '0600'

  - name: Refresh inventory
    meta: refresh_inventory

  tasks:
  - name: Wait for system to become reachable
    wait_for_connection:
      timeout: 60
