---

- name: Verify
  hosts: all

  vars:
    default_fs_type: xfs
    logical_volumes: [] # no /dev/mapper in container, cannot test lv creation
    volume_groups:
      - name: vg.data
        pvs: /dev/loop3,/dev/loop4

    dev_mapping:
    - dev_name: /dev/loop3
      fs_type: lvm

    - dev_name: /dev/loop4
      fs_type: lvm

    - dev_name: /dev/loop5
      mount_path: /var/log

    - dev_name: /dev/loop6
      mount_path: /usr/hdp

    - dev_name: /dev/loop7
      mount_path: /data/01
      mnt_opts: 'defaults,noatime,nofail'

  tasks:
  - name: Assert device is mounted
    assert:
      that: item.dev_name in ansible_mounts | json_query('[*].device')
    loop: "{{ dev_mapping }}"
    when:
    - item.fs_type | default(default_fs_type) != 'lvm'
    - item.dev_name | basename in ansible_devices

# Cannot test LV on docker : no /dev/mapper...
  - name: Assert LV is mounted
    assert:
      that: "'/dev/mapper/{{ item.vg }}-{{ item.name }}' in ansible_mounts | json_query('[*].device')"
    loop: "{{ logical_volumes }}"
    when: logical_volumes | length > 0

...