---

- name: Create volume groups
  become: true
  community.general.lvg:
    vg: "{{ item.name }}"
    pvs: "{{ item.pvs }}"
  loop: "{{ volume_groups }}"

- name: Create logical volumes
  become: true
  community.general.lvol:
    vg: "{{ item.vg }}"
    lv: "{{ item.name }}"
    size: "{{ item.size }}"
  loop: "{{ logical_volumes }}"

- name: Format created logical volumes
  become: true
  community.general.filesystem:
    fstype: "{{ item.fs_type | default(default_fs_type) }}"
    dev: "/dev/mapper/{{ item.vg }}-{{ item.name }}"
    opts: "{{ item.options | default(omit) }}"
  loop: "{{ logical_volumes }}"

- name: Mount formated logical volumes
  become: true
  ansible.posix.mount:
    name: "{{ item.mount_path }}"
    src: "/dev/mapper/{{ item.vg }}-{{ item.name }}"
    fstype: "{{ item.fs_type | default(default_fs_type) }}"
    opts: "{{ item.mnt_opts | default(omit) }}"
    state: mounted
  loop: "{{ logical_volumes }}"

...