---

- name: Gather facts
  when: ansible_devices is not defined
  ansible.builtin.setup:
    gather_subset: '!all,!min,hardware'

- name: Install LVM2 packages
  become: true
  ansible.builtin.package:
    name: lvm2
    state: present
  when: "'lvm' in dev_mapping | json_query('[*].fs_type')"

- name: Install xfsprogs packages
  become: true
  ansible.builtin.package:
    name: xfsprogs
    state: present
  when:
  - ("'xfs' in dev_mapping | json_query('[*].fs_type')") or (default_fs_type == 'xfs')

- name: Format existing block devices
  become: true
  community.general.filesystem:
    fstype: "{{ item.fs_type | default(default_fs_type) }}"
    dev: "{{ item.dev_name }}"
    opts: "{{ item.options | default(omit) }}"
  when: item.dev_name | basename in ansible_devices or fs_skip_existence_check
  loop: "{{ dev_mapping }}"

- name: Mount formated block devices
  become: true
  ansible.posix.mount:
    name: "{{ item.mount_path }}"
    src: "{{ item.dev_name }}"
    fstype: "{{ item.fs_type | default(default_fs_type) }}"
    opts: "{{ item.mnt_opts | default(omit) }}"
    state: mounted
  when:
    - item.fs_type | default(default_fs_type) != 'lvm'
    - item.dev_name | basename in ansible_devices or fs_skip_existence_check
  loop: "{{ dev_mapping }}"

- name: LVM configuration
  ansible.builtin.include_tasks: lvm.yml
  when: "'lvm' in dev_mapping | json_query('[*].fs_type')"

...