---
- name: Converge
  hosts: all
  gather_facts: no
  strategy: free

  vars:
    etc_hosts_group: all
    etc_hosts_file: /etc/hosts2 # Cannot modify /etc/hosts in docker

  roles:
    - role: klusters.system.etc_hosts
