---
- name: Destroy
  hosts: localhost
  connection: local
  gather_facts: false
  vars:
    terraform_dir: "/opt/hostedtoolcache/terraform_destroy/{{ lookup('env','MOLECULE_SCENARIO_NAME')| regex_replace('_','') +
    '-' + lookup('env','MOLECULE_DISTRO') |default('default') }}"

  pre_tasks:
  - name: Get Terraform scripts
    git:
      repo: 'https://github.com/klusters/terraform-tools-gce-molecule'
      dest: '{{ terraform_dir }}'
      version: master

  tasks:
  - name: Terraform destroy
    terraform:
      binary_path: "{{ lookup('env','TERRAFORM_CLI_PATH') + '/terraform-bin' |default(omit) }}"
      force_init: yes
      project_path: '{{ terraform_dir }}'
      workspace: "{{ lookup('env','MOLECULE_SCENARIO_NAME')| regex_replace('_','') + '-' + lookup('env','MOLECULE_DISTRO') |default('default') }}"
      state: absent
    environment:
      TF_VAR_project_id: "{{ lookup('env','TF_VAR_project_id') }}"
      TF_VAR_ssh_public_key: "{{ lookup('env','TF_VAR_ssh_public_key') }}"
      GOOGLE_APPLICATION_CREDENTIALS: "{{ lookup('env','GOOGLE_APPLICATION_CREDENTIALS') }}"
