---

dependency:
  name: galaxy

driver:
  name: delegated

lint: |
  yamllint .
  ansible-lint

platforms:
- name: centos-7-${GITHUB_RUN_NUMBER}-001
  instance_name: centos-7-${GITHUB_RUN_NUMBER}
  region: europe-west1
  network: default
  subnetwork: default
  machine_type: f1-micro
  image: centos-7
  image_project: centos-cloud
  labels:
    molecule_scenario: ${MOLECULE_SCENARIO_NAME}
    molecule_distro: centos-7
  additional_disks: []

- name: centos-8-${GITHUB_RUN_NUMBER}-001
  instance_name: centos-8-${GITHUB_RUN_NUMBER}
  region: europe-west1
  network: default
  subnetwork: default
  machine_type: f1-micro
  image: centos-8
  image_project: centos-cloud
  labels:
    molecule_scenario: ${MOLECULE_SCENARIO_NAME}
    molecule_distro: centos-8
  additional_disks: []

- name: ubuntu-1804-lts-${GITHUB_RUN_NUMBER}-001
  instance_name: ubuntu-1804-lts-${GITHUB_RUN_NUMBER}
  region: europe-west1
  network: default
  subnetwork: default
  machine_type: f1-micro
  image: ubuntu-1804-lts
  image_project: ubuntu-os-cloud
  labels:
    molecule_scenario: ${MOLECULE_SCENARIO_NAME}
    molecule_distro: ubuntu-1804-lts
  additional_disks: []

- name: ubuntu-2004-lts-${GITHUB_RUN_NUMBER}-001
  instance_name: ubuntu-2004-lts-${GITHUB_RUN_NUMBER}
  region: europe-west1
  network: default
  subnetwork: default
  machine_type: f1-micro
  image: ubuntu-2004-lts
  image_project: ubuntu-os-cloud
  labels:
    molecule_scenario: ${MOLECULE_SCENARIO_NAME}
    molecule_distro: ubuntu-2004-lts
  additional_disks: []

provisioner:
  name: ansible
  playbooks:
    converge: ${MOLECULE_PLAYBOOK:-converge.yml}
    create: ../common/create.yml
    destroy: ../common/destroy.yml
    prepare: ../common/prepare.yml
  connection_options:
    ansible_ssh_user: "github-ci"
    ansible_ssh_private_key_file: "~/.ssh/${GITHUB_WORKFLOW}_${GITHUB_RUN_NUMBER}"
    ansible_ssh_common_args: -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null
  ansible_args:
    - --inventory=../common/gce_instances.gcp.yml