name: Ansible Tests

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      PY_COLORS: 1
      ANSIBLE_FORCE_COLOR: 1

    strategy:
      fail-fast: true
      matrix:
        molecule_distro:
          - {"distro":"centos-8", "command":"/usr/sbin/init"}
        collection_role:
          - etc_hosts

    steps:
      - uses: actions/checkout@v2
        with:
          path: ansible_collections/klusters/system

      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
          architecture: x64

      - name: Install dependencies
        run: |
          sudo apt install docker
          python -m pip install --upgrade pip
          pip install molecule yamllint ansible-lint docker

      - name: Run role tests
        run: >-
          molecule --version &&
          ansible --version &&
          molecule test