name: Ansible Tests

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      PY_COLORS: 1
      ANSIBLE_FORCE_COLOR: 1

    strategy:
      fail-fast: true
      matrix:
        python-version: [ '2.x', '3.x' ]
        molecule_distro:
          - { "distro":"centos-7", "command":"/usr/sbin/init" }
          - { "distro":"centos-8", "command":"/usr/sbin/init" }
          - { "distro":"ubuntu-16.04", "command":"/sbin/init" }
          - { "distro":"ubuntu-18.04", "command":"/lib/systemd/systemd" }
          - { "distro":"ubuntu-20.04", "command":"/lib/systemd/systemd" }
          - { "distro":"debian-9", "command":"/lib/systemd/systemd" }
          - { "distro":"debian-10", "command":"/lib/systemd/systemd" }
        collection_role:
          - etc_hosts

    steps:
      - uses: actions/checkout@v2
        with:
          path: ansible_collections/klusters/system

      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64

      - name: Install dependencies
        run: |
          sudo apt install docker
          python -m pip install --upgrade pip
          pip install molecule yamllint ansible-lint docker

      - name: Run role tests
        run: >-
          molecule --version &&
          ansible --version &&
          MOLECULE_COMMAND=${{ matrix.molecule_distro.command }}
          MOLECULE_DISTRO=${{ matrix.molecule_distro.distro }}
          molecule --debug test -s ${{ matrix.collection_role }}