name: Ansible Lint

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    # Important: This sets up your GITHUB_WORKSPACE environment variable
    - uses: actions/checkout@v2

    - name: Play Ansible Playbook
      uses: arillso/action.playbook@master
      with:
        playbook: roles/etc_hosts/tests/playbook.yml
        inventory: roles/etc_hosts/tests/inventory
        galaxy_file: ''
      env:
        ANSIBLE_HOST_KEY_CHECKING: 'false'
        ANSIBLE_DEPRECATION_WARNINGS: 'false'