name: Ansible Tests

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      PY_COLORS: 1
      ANSIBLE_FORCE_COLOR: 1

    strategy:
      fail-fast: true
      matrix:
        molecule_distro:
          - {"distro":"centos-8", "command":"/usr/sbin/init"}
        collection_role:
          - etc_hosts

    steps:
      - uses: actions/checkout@v2
        with:
          path: ansible_collections/klusters/system

      - uses: gofrolist/molecule-action@v2
        molecule_working_dir: ansible_collections/klusters/system