---

name: "klusters.system.filesystems"

on:
  push:
    paths:
    - 'roles/filesystems/**'
    - 'molecule/filesystems/**'
    - '.github/workflows/filesystems.yml'
    - 'molecule/common/**'
    tags_ignore:
      - '*'

jobs:
  molecule:
    runs-on: ubuntu-latest

    env:
      PY_COLORS: 1
      MOLECULE_DISTRO: ${{ matrix.molecule_distro.distro }}
      
    strategy:
      fail-fast: true
      matrix:
        molecule_distro:
        - distro: centos7
        - distro: centos8
        - distro: ubuntu1804
        - distro: ubuntu2004
        collection_role:
        - filesystems

    steps:
    - name: Run molecule test
      uses: klusters/molecule-action@devel
      with:
        checkout_path: ansible_collections/klusters/system
        scenario: ${{ matrix.collection_role }}

...
