---

name: "klusters.system.filesystems"

on:
  push:
    # paths:
    # - 'roles/filesystems/**'
    # - 'molecule/filesystems/**'
    # - '.github/workflows/filesystems.yml'
    # - 'molecule/common/**'

jobs:
  molecule:
    runs-on: ubuntu-latest

    env:
      PY_COLORS: 1
      MOLECULE_DISTRO: ${{ matrix.molecule_distro.distro }}
      
    strategy:
      fail-fast: true
      matrix:
        molecule_distro:
        - distro: centos7
        - distro: centos8
        - distro: ubuntu1804
        - distro: ubuntu2004
        collection_role:
        - filesystems

    steps:
    - name: Git checkout
      uses: actions/checkout@v2
      with:
        path: ansible_collections/klusters/system

    - name: Set up Python 3
      uses: actions/setup-python@v2
      with:
        python-version: 3.x

    - name: Cache python packages
      uses: actions/cache@v2
      with:
        path: ${{ env.pythonLocation }}
        key: ${{ env.pythonLocation }}-${{ hashFiles('**/python_requirements.txt') }}

    - name: Install python packages
      working-directory: ansible_collections/klusters/system
      run: |
        (test -f molecule/${{ matrix.collection_role }}/python_requirements.txt && pip install --upgrade --upgrade-strategy eager -r molecule/${{ matrix.collection_role }}/python_requirements.txt ) ||
        (test -f molecule/common/python_requirements.txt && pip install --upgrade --upgrade-strategy eager -r molecule/common/python_requirements.txt )

    - name: Run tests
      working-directory: ansible_collections/klusters/system
      run: |
        molecule test -s ${{ matrix.collection_role }}

...
